apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      name: nginx
      labels:
        app: java
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
